INFO 2024-12-18 12:11:56,918 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 12:12:08,259 basehttp "GET /aplicatie1/cos_virtual HTTP/1.1" 301 0
INFO 2024-12-18 12:12:08,474 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 4463
WARNING 2024-12-18 12:12:08,531 log Not Found: /favicon.ico
WARNING 2024-12-18 12:12:08,532 basehttp "GET /favicon.ico HTTP/1.1" 404 2372
INFO 2024-12-18 12:12:42,086 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 4503
INFO 2024-12-18 12:12:53,034 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 4503
INFO 2024-12-18 12:16:59,165 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 4565
INFO 2024-12-18 12:17:22,620 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 4602
INFO 2024-12-18 12:17:34,435 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 4565
INFO 2024-12-18 12:23:46,521 autoreload C:\Users\Matei\proiect_django\aplicatie1\models.py changed, reloading.
INFO 2024-12-18 12:23:49,430 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 12:30:33,233 autoreload C:\Users\Matei\proiect_django\aplicatie1\urls.py changed, reloading.
INFO 2024-12-18 12:30:33,757 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:20:43,455 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:23:31,121 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:23:57,287 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:24:30,918 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5444
WARNING 2024-12-18 14:24:31,103 log Not Found: /favicon.ico
WARNING 2024-12-18 14:24:31,103 basehttp "GET /favicon.ico HTTP/1.1" 404 2372
WARNING 2024-12-18 14:24:39,167 log Not Found: /cumpara_cos
WARNING 2024-12-18 14:24:39,168 basehttp "POST /cumpara_cos HTTP/1.1" 404 2373
INFO 2024-12-18 14:26:01,456 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 14:26:02,397 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:27:19,732 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 14:27:20,586 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:27:47,193 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5444
WARNING 2024-12-18 14:27:49,655 log Not Found: /cumpara_cos
WARNING 2024-12-18 14:27:49,656 basehttp "POST /cumpara_cos HTTP/1.1" 404 2373
INFO 2024-12-18 14:30:57,390 autoreload C:\Users\Matei\proiect_django\aplicatie1\urls.py changed, reloading.
INFO 2024-12-18 14:30:58,181 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:31:14,511 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 14:31:15,531 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:31:20,041 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5444
WARNING 2024-12-18 14:31:23,144 log Not Found: /cumpara_cos
WARNING 2024-12-18 14:31:23,146 basehttp "POST /cumpara_cos HTTP/1.1" 404 2373
INFO 2024-12-18 14:33:46,776 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 14:33:47,754 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:35:14,828 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 14:35:15,737 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:35:18,627 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 14:35:19,478 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:38:13,483 basehttp "GET /admin/ HTTP/1.1" 200 16694
INFO 2024-12-18 14:38:13,554 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2024-12-18 14:38:13,555 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2024-12-18 14:38:13,558 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2024-12-18 14:38:13,558 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2024-12-18 14:38:13,559 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2024-12-18 14:38:13,560 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:13,567 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:13,611 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2024-12-18 14:38:13,611 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
WARNING 2024-12-18 14:38:13,675 log Not Found: /favicon.ico
WARNING 2024-12-18 14:38:13,677 basehttp "GET /favicon.ico HTTP/1.1" 404 2372
INFO 2024-12-18 14:38:15,214 basehttp "GET /admin/auth/group/ HTTP/1.1" 200 14242
INFO 2024-12-18 14:38:15,241 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,246 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,248 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,248 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,248 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,248 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,255 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,255 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,255 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,256 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,271 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:15,346 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-12-18 14:38:15,377 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2024-12-18 14:38:16,743 basehttp "GET /admin/auth/group/2/change/ HTTP/1.1" 200 20378
INFO 2024-12-18 14:38:16,775 basehttp "GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:16,775 basehttp "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
INFO 2024-12-18 14:38:16,837 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-12-18 14:38:16,882 basehttp "GET /static/admin/img/selector-icons.svg HTTP/1.1" 304 0
INFO 2024-12-18 14:38:16,882 basehttp "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 304 0
INFO 2024-12-18 14:38:16,882 basehttp "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 304 0
INFO 2024-12-18 14:39:34,222 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5445
WARNING 2024-12-18 14:39:36,181 log Not Found: /cumpara_cos/
WARNING 2024-12-18 14:39:36,186 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
INFO 2024-12-18 14:40:13,303 autoreload C:\Users\Matei\proiect_django\aplicatie1\urls.py changed, reloading.
INFO 2024-12-18 14:40:14,266 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:40:17,909 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5445
WARNING 2024-12-18 14:40:18,989 log Not Found: /cumpara_cos/
WARNING 2024-12-18 14:40:18,989 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
INFO 2024-12-18 14:41:07,274 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 14:41:08,296 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:41:11,718 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5445
WARNING 2024-12-18 14:41:12,678 log Not Found: /cumpara_cos/
WARNING 2024-12-18 14:41:12,679 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
WARNING 2024-12-18 14:41:29,221 log Not Found: /aplicatie1/cuser_lo
WARNING 2024-12-18 14:41:29,221 basehttp "GET /aplicatie1/cuser_lo HTTP/1.1" 404 15946
INFO 2024-12-18 14:41:35,105 basehttp "GET /aplicatie1/user_login HTTP/1.1" 301 0
INFO 2024-12-18 14:41:35,182 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 835
INFO 2024-12-18 14:41:45,614 views Autentificare reusita pentru utilizatorul viceroy.
INFO 2024-12-18 14:41:45,631 basehttp "POST /aplicatie1/user_login/ HTTP/1.1" 302 0
INFO 2024-12-18 14:41:45,785 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 1204
INFO 2024-12-18 14:41:51,372 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5445
WARNING 2024-12-18 14:41:57,107 log Not Found: /cumpara_cos/
WARNING 2024-12-18 14:41:57,109 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
INFO 2024-12-18 14:43:50,688 autoreload C:\Users\Matei\proiect_django\aplicatie1\urls.py changed, reloading.
INFO 2024-12-18 14:43:51,498 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:44:01,992 basehttp "GET /aplicatie1/cumpara_cos HTTP/1.1" 301 0
WARNING 2024-12-18 14:44:02,311 log Method Not Allowed: /aplicatie1/cumpara_cos/
WARNING 2024-12-18 14:44:02,312 basehttp "GET /aplicatie1/cumpara_cos/ HTTP/1.1" 405 29
INFO 2024-12-18 14:46:56,734 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5445
INFO 2024-12-18 14:51:01,172 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5673
WARNING 2024-12-18 14:51:02,934 log Not Found: /cumpara_cos/
WARNING 2024-12-18 14:51:02,935 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
INFO 2024-12-18 14:55:13,361 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 14:55:14,347 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 14:55:16,550 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5876
WARNING 2024-12-18 14:55:19,267 log Not Found: /cumpara_cos/
WARNING 2024-12-18 14:55:19,267 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
INFO 2024-12-18 14:56:58,315 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5475
WARNING 2024-12-18 14:56:59,777 log Not Found: /cumpara_cos/
WARNING 2024-12-18 14:56:59,778 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
INFO 2024-12-18 14:58:24,361 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 1089
WARNING 2024-12-18 14:58:54,421 log Method Not Allowed: /aplicatie1/cumpara_cos/
WARNING 2024-12-18 14:58:54,421 basehttp "GET /aplicatie1/cumpara_cos/ HTTP/1.1" 405 55
INFO 2024-12-18 15:03:56,244 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5549
WARNING 2024-12-18 15:03:58,529 log Not Found: /cumpara_cos/
WARNING 2024-12-18 15:03:58,531 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
INFO 2024-12-18 15:16:07,799 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:16:08,881 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:16:21,432 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5418
WARNING 2024-12-18 15:16:22,968 log Not Found: /cumpara_cos/
WARNING 2024-12-18 15:16:22,969 basehttp "POST /cumpara_cos/ HTTP/1.1" 404 2376
INFO 2024-12-18 15:17:52,362 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5429
ERROR 2024-12-18 15:17:54,236 log Internal Server Error: /aplicatie1/cumpara_cos/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 698, in cumpara_cos
    for item in cos_virtual.split(","):
                ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
ERROR 2024-12-18 15:17:54,238 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 500 76887
INFO 2024-12-18 15:19:37,726 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:19:38,817 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:19:40,057 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5429
ERROR 2024-12-18 15:19:41,197 log Internal Server Error: /aplicatie1/cumpara_cos/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 699, in cumpara_cos
    for item in cos_virtual.split(","):
                ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
ERROR 2024-12-18 15:19:41,199 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 500 76874
INFO 2024-12-18 15:22:18,122 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:22:18,961 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:22:49,715 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5429
ERROR 2024-12-18 15:23:02,554 log Internal Server Error: /aplicatie1/cumpara_cos/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 720, in cumpara_cos
    email.send()
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
                       ^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\django\core\mail\backends\smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 841, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed
ERROR 2024-12-18 15:23:02,569 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 500 114828
INFO 2024-12-18 15:23:50,014 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:23:53,312 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5429
WARNING 2024-12-18 15:23:59,461 log Bad Request: /aplicatie1/cumpara_cos/
WARNING 2024-12-18 15:23:59,461 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 400 53
INFO 2024-12-18 15:26:13,996 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 1089
INFO 2024-12-18 15:26:32,310 views Utilizatorul viceroy s-a deconectat.
INFO 2024-12-18 15:26:32,322 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2024-12-18 15:26:32,421 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 952
INFO 2024-12-18 15:27:32,316 views Autentificare reusita pentru utilizatorul viceroy.
INFO 2024-12-18 15:27:32,319 basehttp "POST /aplicatie1/user_login/ HTTP/1.1" 302 0
INFO 2024-12-18 15:27:32,401 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 1204
INFO 2024-12-18 15:27:36,464 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5429
WARNING 2024-12-18 15:27:40,202 log Bad Request: /aplicatie1/cumpara_cos/
WARNING 2024-12-18 15:27:40,204 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 400 53
INFO 2024-12-18 15:28:13,553 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:28:14,295 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:33:14,650 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:33:15,558 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:33:20,147 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5429
WARNING 2024-12-18 15:33:28,674 log Bad Request: /aplicatie1/cumpara_cos/
WARNING 2024-12-18 15:33:28,674 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 400 53
INFO 2024-12-18 15:35:17,400 basehttp "GET /aplicatie1/lista_produse HTTP/1.1" 301 0
INFO 2024-12-18 15:35:17,801 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19453
INFO 2024-12-18 15:37:02,194 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:37:03,050 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:40:37,192 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:40:38,261 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:40:44,201 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19453
INFO 2024-12-18 15:40:50,231 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5429
WARNING 2024-12-18 15:40:52,742 log Bad Request: /aplicatie1/cumpara_cos/
WARNING 2024-12-18 15:40:52,743 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 400 53
INFO 2024-12-18 15:41:29,640 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5429
INFO 2024-12-18 15:41:56,911 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 200 69
INFO 2024-12-18 15:42:42,295 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:42:42,949 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:43:00,166 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2024-12-18 15:43:00,816 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:46:55,078 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:52:33,077 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19453
INFO 2024-12-18 15:52:53,647 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5424
INFO 2024-12-18 15:53:00,090 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 200 69
INFO 2024-12-18 15:53:46,809 basehttp "GET /admin/ HTTP/1.1" 200 16694
INFO 2024-12-18 15:55:08,091 autoreload C:\Users\Matei\proiect_django\aplicatie1\admin.py changed, reloading.
INFO 2024-12-18 15:55:08,989 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:55:29,603 autoreload C:\Users\Matei\proiect_django\aplicatie1\admin.py changed, reloading.
INFO 2024-12-18 15:55:30,572 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:55:43,389 autoreload C:\Users\Matei\proiect_django\aplicatie1\admin.py changed, reloading.
INFO 2024-12-18 15:55:44,109 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:57:39,116 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 15:57:42,530 basehttp "GET /admin/ HTTP/1.1" 200 17315
INFO 2024-12-18 15:57:45,793 basehttp "GET /admin/aplicatie1/comanda/ HTTP/1.1" 200 20679
INFO 2024-12-18 15:57:45,902 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-12-18 15:57:45,930 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
INFO 2024-12-18 15:57:45,933 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
INFO 2024-12-18 16:01:48,951 autoreload Watching for file changes with StatReloader
INFO 2024-12-18 16:13:01,390 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19453
INFO 2024-12-18 16:13:58,059 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 5424
INFO 2024-12-18 16:14:31,716 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 200 69
INFO 2024-12-18 16:23:32,175 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19453
INFO 2024-12-18 16:23:41,126 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 6096
INFO 2024-12-18 16:25:15,975 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 6202
INFO 2024-12-18 16:25:26,908 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 200 69
INFO 2025-01-03 17:45:18,443 autoreload Watching for file changes with StatReloader
INFO 2025-01-03 17:46:30,250 autoreload Watching for file changes with StatReloader
INFO 2025-01-03 17:51:13,845 autoreload Watching for file changes with StatReloader
INFO 2025-01-03 17:52:36,301 autoreload Watching for file changes with StatReloader
INFO 2025-01-03 17:53:44,486 autoreload Watching for file changes with StatReloader
INFO 2025-01-03 17:54:32,881 autoreload Watching for file changes with StatReloader
INFO 2025-01-03 17:54:37,840 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2025-01-03 17:54:37,972 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
INFO 2025-01-03 17:54:38,123 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22092
INFO 2025-01-03 17:54:38,140 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
INFO 2025-01-03 17:54:38,141 basehttp "GET /static/admin/css/login.css HTTP/1.1" 200 951
INFO 2025-01-03 17:54:38,141 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
INFO 2025-01-03 17:54:38,141 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-01-03 17:54:38,147 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-01-03 17:54:38,159 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
WARNING 2025-01-03 17:54:38,230 log Not Found: /favicon.ico
WARNING 2025-01-03 17:54:38,231 basehttp "GET /favicon.ico HTTP/1.1" 404 2372
INFO 2025-01-03 17:54:43,051 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-01-03 17:54:43,153 basehttp "GET /admin/ HTTP/1.1" 200 17315
INFO 2025-01-03 17:54:43,180 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2025-01-03 17:54:43,194 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-01-03 17:54:43,194 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-01-03 17:54:45,054 basehttp "GET /admin/auth/group/ HTTP/1.1" 200 14682
INFO 2025-01-03 17:54:45,082 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-01-03 17:54:45,085 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-01-03 17:54:45,100 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-01-03 17:54:45,101 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-01-03 17:54:45,102 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
INFO 2025-01-03 17:54:45,110 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-01-03 17:54:45,112 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-01-03 17:54:45,124 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-01-03 17:54:45,134 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-01-03 17:54:45,170 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-03 17:54:45,185 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-01-03 17:54:45,227 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-01-03 17:54:45,249 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-01-03 17:54:46,747 basehttp "GET /admin/auth/group/3/change/ HTTP/1.1" 200 20791
INFO 2025-01-03 17:54:46,774 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 200 8794
INFO 2025-01-03 17:54:46,778 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-01-03 17:54:46,783 basehttp "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15502
INFO 2025-01-03 17:54:46,784 basehttp "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2025-01-03 17:54:46,788 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
INFO 2025-01-03 17:54:46,802 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-01-03 17:54:46,820 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-03 17:54:46,858 basehttp "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2025-01-03 17:54:46,859 basehttp "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2025-01-03 17:54:46,859 basehttp "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2025-01-03 18:00:12,381 basehttp "POST /admin/logout/ HTTP/1.1" 302 0
INFO 2025-01-03 18:00:12,407 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 835
INFO 2025-01-03 18:00:18,704 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2025-01-03 18:00:18,712 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
INFO 2025-01-03 18:00:18,758 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-01-03 18:00:18,758 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-01-03 18:00:18,758 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-01-03 18:00:18,758 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-01-03 18:00:18,759 basehttp "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2025-01-03 18:00:18,759 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-01-03 18:00:18,765 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-01-03 18:00:29,006 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4321
INFO 2025-01-06 19:10:34,331 autoreload Watching for file changes with StatReloader
INFO 2025-01-06 19:10:43,132 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 302 0
INFO 2025-01-06 19:10:43,256 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/profile/ HTTP/1.1" 200 835
WARNING 2025-01-06 19:10:43,446 log Not Found: /favicon.ico
WARNING 2025-01-06 19:10:43,447 basehttp "GET /favicon.ico HTTP/1.1" 404 2372
INFO 2025-01-06 19:10:53,156 views Autentificare reusita pentru utilizatorul grief.
INFO 2025-01-06 19:10:53,160 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/profile/ HTTP/1.1" 302 0
INFO 2025-01-06 19:10:53,282 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 1204
INFO 2025-01-06 19:11:02,829 basehttp "GET /aplicatie1/cos_virtual HTTP/1.1" 301 0
INFO 2025-01-06 19:11:02,983 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 6202
INFO 2025-01-06 19:11:10,865 basehttp "GET /aplicatie1/lista_produse HTTP/1.1" 301 0
INFO 2025-01-06 19:11:11,327 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19453
INFO 2025-01-06 19:38:30,823 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19629
INFO 2025-01-06 19:42:01,330 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19674
INFO 2025-01-06 19:42:51,275 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19674
INFO 2025-01-06 20:01:29,158 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19674
INFO 2025-01-06 20:04:26,610 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19848
INFO 2025-01-06 20:08:03,486 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 20296
INFO 2025-01-06 20:11:33,707 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19618
INFO 2025-01-06 20:11:35,685 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19618
INFO 2025-01-06 20:11:38,056 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19618
INFO 2025-01-06 20:16:33,435 autoreload Watching for file changes with StatReloader
INFO 2025-01-06 20:18:32,560 autoreload Watching for file changes with StatReloader
INFO 2025-01-06 20:18:36,027 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19567
INFO 2025-01-06 20:19:50,854 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 6202
INFO 2025-01-06 20:19:59,283 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 200 69
INFO 2025-01-06 20:20:11,386 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 1089
INFO 2025-01-06 20:33:21,619 autoreload Watching for file changes with StatReloader
INFO 2025-01-06 20:33:23,873 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19567
INFO 2025-01-06 20:33:32,958 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 6202
WARNING 2025-01-06 20:34:07,251 log Not Found: /aplicatie1/produs_detail/6
WARNING 2025-01-06 20:34:07,252 basehttp "GET /aplicatie1/produs_detail/6 HTTP/1.1" 404 15967
WARNING 2025-01-06 20:34:13,134 log Not Found: /aplicatie1/produs_detail/7
WARNING 2025-01-06 20:34:13,135 basehttp "GET /aplicatie1/produs_detail/7 HTTP/1.1" 404 15967
WARNING 2025-01-06 20:34:15,524 log Not Found: /aplicatie1/produs_detail/8
WARNING 2025-01-06 20:34:15,525 basehttp "GET /aplicatie1/produs_detail/8 HTTP/1.1" 404 15967
WARNING 2025-01-06 20:34:18,066 log Not Found: /aplicatie1/produs_detail/9
WARNING 2025-01-06 20:34:18,067 basehttp "GET /aplicatie1/produs_detail/9 HTTP/1.1" 404 15967
WARNING 2025-01-06 20:34:22,665 log Not Found: /aplicatie1/produs_detail/14
WARNING 2025-01-06 20:34:22,667 basehttp "GET /aplicatie1/produs_detail/14 HTTP/1.1" 404 15970
WARNING 2025-01-06 20:34:46,657 log Not Found: /aplicatie1/produs_detail/
WARNING 2025-01-06 20:34:46,659 basehttp "GET /aplicatie1/produs_detail/ HTTP/1.1" 404 15964
INFO 2025-01-06 20:34:59,408 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 19567
INFO 2025-01-06 20:35:00,775 basehttp "GET /aplicatie1/produs/11/ HTTP/1.1" 200 9525
INFO 2025-01-06 20:35:06,489 basehttp "GET /aplicatie1/produs/7/ HTTP/1.1" 200 9526
INFO 2025-01-06 20:35:11,558 basehttp "GET /aplicatie1/produs/13/ HTTP/1.1" 200 9523
INFO 2025-01-06 20:38:18,005 basehttp "GET /aplicatie1/produs/13/ HTTP/1.1" 200 18157
INFO 2025-01-06 20:38:21,595 basehttp "GET /aplicatie1/produs/13/ HTTP/1.1" 200 18157
INFO 2025-01-07 11:11:20,602 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 11:11:23,768 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2025-01-07 11:11:23,912 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
INFO 2025-01-07 11:11:23,952 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:23,953 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:23,953 basehttp "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:23,954 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:23,954 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:23,954 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:23,958 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
WARNING 2025-01-07 11:11:24,074 log Not Found: /favicon.ico
WARNING 2025-01-07 11:11:24,075 basehttp "GET /favicon.ico HTTP/1.1" 404 2372
INFO 2025-01-07 11:11:26,732 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-01-07 11:11:26,814 basehttp "GET /admin/ HTTP/1.1" 200 17315
INFO 2025-01-07 11:11:26,832 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:26,837 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2025-01-07 11:11:26,837 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,471 basehttp "GET /admin/auth/group/ HTTP/1.1" 200 14682
INFO 2025-01-07 11:11:28,497 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,497 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,498 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,498 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,498 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,501 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,501 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,502 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,503 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,503 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,511 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:28,572 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 11:11:28,592 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,672 basehttp "GET /admin/auth/group/3/change/ HTTP/1.1" 200 20791
INFO 2025-01-07 11:11:30,696 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,697 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,697 basehttp "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,697 basehttp "GET /static/admin/js/SelectBox.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,700 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,703 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,747 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 11:11:30,779 basehttp "GET /static/admin/img/selector-icons.svg HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,779 basehttp "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 304 0
INFO 2025-01-07 11:11:30,779 basehttp "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 304 0
WARNING 2025-01-07 11:16:21,056 log Not Found: /
WARNING 2025-01-07 11:16:21,057 basehttp "GET / HTTP/1.1" 404 2321
INFO 2025-01-07 11:17:29,332 basehttp "GET /admin/auth/group/ HTTP/1.1" 200 14682
INFO 2025-01-07 11:17:30,556 basehttp "GET /admin/auth/group/2/change/ HTTP/1.1" 200 20816
INFO 2025-01-07 11:17:30,627 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 11:35:12,476 basehttp "GET /admin/auth/group/ HTTP/1.1" 200 14682
INFO 2025-01-07 11:35:25,528 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 302 0
ERROR 2025-01-07 11:35:25,780 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:35:25,787 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/profile/ HTTP/1.1" 500 220428
WARNING 2025-01-07 11:35:25,935 log Not Found: /favicon.ico
WARNING 2025-01-07 11:35:25,936 basehttp "GET /favicon.ico HTTP/1.1" 404 2372
ERROR 2025-01-07 11:37:25,136 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:37:25,140 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/profile/ HTTP/1.1" 500 220561
ERROR 2025-01-07 11:37:29,706 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:37:29,710 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 219862
ERROR 2025-01-07 11:39:15,105 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:39:15,110 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 243966
INFO 2025-01-07 11:39:25,728 basehttp "GET /aplicatie1/user_logout HTTP/1.1" 301 0
INFO 2025-01-07 11:39:26,040 views Utilizatorul  s-a deconectat.
INFO 2025-01-07 11:39:26,102 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
ERROR 2025-01-07 11:39:26,214 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:39:26,220 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 243978
ERROR 2025-01-07 11:40:50,020 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='Moderatori').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 466, in user_login
    return render(request, 'login.html', {'form': form})
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 208, in select_template
    return self.get_template(template_name)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='Moderatori').exists' from 'user.groups.filter(name='Moderatori').exists'
ERROR 2025-01-07 11:40:50,025 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 244462
INFO 2025-01-07 11:54:33,968 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 11:54:34,804 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 11:58:55,100 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 11:58:55,788 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:02:39,743 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:02:40,483 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:05:56,853 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:05:57,489 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:11:03,034 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:11:03,705 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:11:09,133 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:11:09,809 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:27:32,266 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:27:32,899 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:28:44,997 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:28:45,712 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:29:30,490 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:29:31,171 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:30:40,282 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:30:40,927 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:31:38,881 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:31:39,562 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:32:27,418 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:32:28,071 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:33:12,929 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:33:13,636 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:34:28,791 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:34:29,440 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:37:14,574 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:37:15,262 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:38:32,683 autoreload Watching for file changes with StatReloader
ERROR 2025-01-07 12:38:50,094 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 494, in user_login
    return render(request, 'login.html', context)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'filtrare_filme_2' not found. 'filtrare_filme_2' is not a valid view function or pattern name.
ERROR 2025-01-07 12:38:50,098 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 147252
INFO 2025-01-07 12:39:28,685 autoreload C:\Users\Matei\proiect_django\aplicatie1\urls.py changed, reloading.
INFO 2025-01-07 12:39:29,333 autoreload Watching for file changes with StatReloader
ERROR 2025-01-07 12:39:31,792 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 494, in user_login
    return render(request, 'login.html', context)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contact' not found. 'contact' is not a valid view function or pattern name.
ERROR 2025-01-07 12:39:31,795 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 500 147077
INFO 2025-01-07 12:39:44,913 autoreload C:\Users\Matei\proiect_django\aplicatie1\urls.py changed, reloading.
INFO 2025-01-07 12:39:45,632 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:39:46,670 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 12:39:58,595 basehttp "GET /aplicatie1/lista_filme/ HTTP/1.1" 200 1820
INFO 2025-01-07 12:40:00,583 basehttp "GET /aplicatie1/filtrare_filme_2/ HTTP/1.1" 200 2978
INFO 2025-01-07 12:40:02,237 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 20677
INFO 2025-01-07 12:40:10,145 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 12:40:15,190 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 12:40:15,257 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 12:45:10,556 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:45:11,248 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:45:20,226 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 12:47:39,154 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 12:47:39,327 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 12:47:42,119 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 12:47:43,327 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 12:47:43,395 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 12:48:27,145 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:48:27,781 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:48:30,912 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 12:48:32,466 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 12:48:32,519 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 12:49:38,919 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:49:39,557 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:49:41,805 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 12:49:43,217 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 12:49:43,270 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 12:51:09,951 autoreload C:\Users\Matei\proiect_django\aplicatie1\urls.py changed, reloading.
INFO 2025-01-07 12:51:10,644 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 12:51:18,658 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 12:51:19,806 basehttp "GET /aplicatie1/filtrare_filme_2/ HTTP/1.1" 200 2978
INFO 2025-01-07 12:51:21,098 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 20677
INFO 2025-01-07 12:51:22,552 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 12:51:23,609 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 302 0
INFO 2025-01-07 12:51:23,679 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/profile/ HTTP/1.1" 200 1942
INFO 2025-01-07 12:51:27,830 basehttp "GET /aplicatie1/filtrare_filme_2/ HTTP/1.1" 200 2978
INFO 2025-01-07 12:51:29,157 basehttp "GET /aplicatie1/lista_filme/ HTTP/1.1" 200 1820
INFO 2025-01-07 12:51:30,079 basehttp "GET /aplicatie1/lista_cinemauri/ HTTP/1.1" 200 1898
INFO 2025-01-07 12:51:30,746 basehttp "GET /aplicatie1/contact HTTP/1.1" 200 2955
INFO 2025-01-07 12:51:32,716 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 1942
INFO 2025-01-07 12:51:34,871 basehttp "GET /aplicatie1/register/ HTTP/1.1" 200 3783
INFO 2025-01-07 12:51:37,140 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 12:51:41,861 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 12:51:41,917 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
WARNING 2025-01-07 12:53:18,872 log Not Found: /aplicatie1/compara_cos
WARNING 2025-01-07 12:53:18,872 basehttp "GET /aplicatie1/compara_cos HTTP/1.1" 404 16020
INFO 2025-01-07 12:53:24,952 basehttp "GET /aplicatie1/cumpara_cos HTTP/1.1" 301 0
INFO 2025-01-07 12:53:25,330 basehttp "GET /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 12:53:25,495 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 12:53:46,336 basehttp "GET /admin/ HTTP/1.1" 200 17315
INFO 2025-01-07 12:53:55,662 basehttp "GET /admin/aplicatie1/customuser/ HTTP/1.1" 200 21695
INFO 2025-01-07 12:53:55,737 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 12:53:55,804 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-01-07 12:53:55,805 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2025-01-07 12:53:55,893 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-01-07 12:53:55,893 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
ERROR 2025-01-07 12:54:21,592 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 474, in user_login
    if (current_time - time) < datetime.timedelta(minutes=2)
                               ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
ERROR 2025-01-07 12:54:21,595 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 500 72323
INFO 2025-01-07 12:56:37,053 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:56:37,842 autoreload Watching for file changes with StatReloader
ERROR 2025-01-07 12:56:42,262 log Internal Server Error: /aplicatie1/user_login/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 474, in user_login
    if (current_time - time) < datetime.timedelta(minutes=2)
                               ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
ERROR 2025-01-07 12:56:42,264 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 500 72323
INFO 2025-01-07 12:56:50,542 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 12:56:51,235 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 13:00:05,577 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 13:00:06,262 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 13:00:16,384 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 2104
INFO 2025-01-07 13:00:23,945 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 2104
INFO 2025-01-07 13:00:55,991 views Autentificare reusita pentru utilizatorul genghischan.
INFO 2025-01-07 13:00:55,993 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:00:56,056 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2218
INFO 2025-01-07 13:01:02,463 views Utilizatorul genghischan s-a deconectat.
INFO 2025-01-07 13:01:02,476 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2025-01-07 13:01:02,539 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 13:01:04,396 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 13:01:05,981 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:01:06,035 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 13:01:14,586 basehttp "GET /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:01:14,655 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 13:01:35,126 views Autentificare reusita pentru utilizatorul genghischan.
INFO 2025-01-07 13:01:35,128 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:01:35,186 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2218
INFO 2025-01-07 13:05:20,509 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 13:05:21,239 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 13:06:09,839 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2103
INFO 2025-01-07 13:06:13,837 views Utilizatorul genghischan s-a deconectat.
INFO 2025-01-07 13:06:13,850 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2025-01-07 13:06:13,906 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 13:06:15,295 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7506
INFO 2025-01-07 13:06:16,856 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:06:16,903 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 13:06:58,475 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7522
INFO 2025-01-07 13:06:59,947 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:06:59,999 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 13:07:54,985 basehttp "GET /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:07:55,041 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 13:08:02,198 views Autentificare reusita pentru utilizatorul genghischan.
INFO 2025-01-07 13:08:02,200 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:08:02,249 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2218
INFO 2025-01-07 13:08:17,435 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 13:08:18,152 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 13:08:18,599 views Utilizatorul genghischan s-a deconectat.
INFO 2025-01-07 13:08:18,615 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2025-01-07 13:08:18,674 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 13:08:19,217 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7312
INFO 2025-01-07 13:08:20,609 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:08:20,655 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 13:08:24,543 basehttp "GET /aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:08:24,592 basehttp "GET /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 200 1942
INFO 2025-01-07 13:08:34,739 views Autentificare reusita pentru utilizatorul genghischan.
INFO 2025-01-07 13:08:34,741 basehttp "POST /aplicatie1/user_login/?next=/aplicatie1/cumpara_cos/ HTTP/1.1" 302 0
INFO 2025-01-07 13:08:34,805 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2218
INFO 2025-01-07 13:08:38,884 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7209
INFO 2025-01-07 13:08:42,008 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 200 69
INFO 2025-01-07 13:47:45,585 autoreload C:\Users\Matei\proiect_django\aplicatie1\views.py changed, reloading.
INFO 2025-01-07 13:47:46,258 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 13:47:49,498 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7468
INFO 2025-01-07 13:47:52,765 views Utilizatorul genghischan s-a deconectat.
INFO 2025-01-07 13:47:52,780 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2025-01-07 13:47:52,841 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 13:47:56,500 basehttp "GET /aplicatie1/lista_produse/ HTTP/1.1" 200 20677
INFO 2025-01-07 13:47:59,904 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7572
WARNING 2025-01-07 13:48:02,089 log Not Found: /login
WARNING 2025-01-07 13:48:02,090 basehttp "GET /login HTTP/1.1" 404 2354
INFO 2025-01-07 13:48:26,294 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7576
WARNING 2025-01-07 13:48:27,666 log Not Found: /aplicatie1/cos_virtual/url /login
WARNING 2025-01-07 13:48:27,666 basehttp "GET /aplicatie1/cos_virtual/url%20/login HTTP/1.1" 404 16055
INFO 2025-01-07 13:48:42,947 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7604
WARNING 2025-01-07 13:48:44,207 log Not Found: /aplicatie1/login
WARNING 2025-01-07 13:48:44,208 basehttp "GET /aplicatie1/login HTTP/1.1" 404 16002
WARNING 2025-01-07 13:48:59,017 log Not Found: /aplicatie1/login
WARNING 2025-01-07 13:48:59,018 basehttp "GET /aplicatie1/login HTTP/1.1" 404 16002
INFO 2025-01-07 13:49:02,229 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7609
INFO 2025-01-07 13:49:03,052 basehttp "GET /aplicatie1/user_login HTTP/1.1" 301 0
INFO 2025-01-07 13:49:03,412 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 1942
INFO 2025-01-07 13:49:15,819 views Autentificare reusita pentru utilizatorul jerma985.
INFO 2025-01-07 13:49:15,821 basehttp "POST /aplicatie1/user_login/ HTTP/1.1" 302 0
INFO 2025-01-07 13:49:15,870 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2221
INFO 2025-01-07 13:49:17,614 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7505
INFO 2025-01-07 13:49:27,939 basehttp "POST /aplicatie1/cumpara_cos/ HTTP/1.1" 200 69
INFO 2025-01-07 13:50:42,255 views Utilizatorul jerma985 s-a deconectat.
INFO 2025-01-07 13:50:42,269 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2025-01-07 13:50:42,321 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 13:50:55,014 views Autentificare reusita pentru utilizatorul viceroy.
INFO 2025-01-07 13:50:55,016 basehttp "POST /aplicatie1/user_login/ HTTP/1.1" 302 0
ERROR 2025-01-07 13:50:55,263 log Internal Server Error: /aplicatie1/profile/
Traceback (most recent call last):
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Matei\proiect_django\aplicatie1\views.py", line 515, in profile
    return render(request, 'profile.html', context)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matei\AppData\Roaming\Python\Python313\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'promotii' not found. 'promotii' is not a valid view function or pattern name.
ERROR 2025-01-07 13:50:55,267 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 500 173376
INFO 2025-01-07 13:51:15,417 autoreload C:\Users\Matei\proiect_django\aplicatie1\urls.py changed, reloading.
INFO 2025-01-07 13:51:16,190 autoreload Watching for file changes with StatReloader
INFO 2025-01-07 13:51:17,084 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2657
INFO 2025-01-07 13:51:20,024 basehttp "GET /aplicatie1/lista_utilizatori/ HTTP/1.1" 200 2177
INFO 2025-01-07 13:51:23,106 basehttp "GET /aplicatie1/utilizator/9/ HTTP/1.1" 200 2122
INFO 2025-01-07 13:51:25,376 basehttp "GET /aplicatie1/promotii/ HTTP/1.1" 200 3088
INFO 2025-01-07 13:51:45,211 basehttp "GET /aplicatie1/creare_angajati/ HTTP/1.1" 200 4660
INFO 2025-01-07 13:52:58,546 basehttp "GET /admin/ HTTP/1.1" 200 17315
INFO 2025-01-07 13:53:03,439 basehttp "GET /admin/auth/group/ HTTP/1.1" 200 14682
INFO 2025-01-07 13:53:03,506 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:53:04,442 basehttp "GET /admin/ HTTP/1.1" 200 17315
INFO 2025-01-07 13:53:07,815 basehttp "GET /admin/aplicatie1/customuser/ HTTP/1.1" 200 21695
INFO 2025-01-07 13:53:07,872 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:53:10,014 basehttp "GET /admin/aplicatie1/customuser/10/change/ HTTP/1.1" 200 36075
INFO 2025-01-07 13:53:10,086 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:53:10,104 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-01-07 13:53:10,111 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-01-07 13:53:10,130 basehttp "GET /static/admin/img/tooltag-arrowright.svg HTTP/1.1" 200 280
INFO 2025-01-07 13:53:10,154 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-01-07 13:53:10,154 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-01-07 13:53:12,661 basehttp "GET /admin/aplicatie1/customuser/ HTTP/1.1" 200 21695
INFO 2025-01-07 13:53:14,215 basehttp "GET /admin/aplicatie1/customuser/6/change/ HTTP/1.1" 200 36055
INFO 2025-01-07 13:53:14,273 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:53:16,264 basehttp "GET /admin/aplicatie1/customuser/ HTTP/1.1" 200 21695
INFO 2025-01-07 13:53:17,167 basehttp "GET /admin/aplicatie1/customuser/9/change/ HTTP/1.1" 200 36031
INFO 2025-01-07 13:53:17,233 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:53:18,386 basehttp "GET /admin/aplicatie1/customuser/ HTTP/1.1" 200 21695
INFO 2025-01-07 13:53:19,361 basehttp "GET /admin/aplicatie1/customuser/11/change/ HTTP/1.1" 200 36070
INFO 2025-01-07 13:53:19,427 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:53:20,646 basehttp "GET /admin/aplicatie1/customuser/ HTTP/1.1" 200 21695
INFO 2025-01-07 13:53:21,541 basehttp "GET /admin/aplicatie1/customuser/12/change/ HTTP/1.1" 200 36064
INFO 2025-01-07 13:53:21,607 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:54:52,158 basehttp "GET /admin/aplicatie1/customuser/ HTTP/1.1" 200 21695
INFO 2025-01-07 13:54:53,979 basehttp "GET /admin/aplicatie1/customuser/9/change/ HTTP/1.1" 200 36031
INFO 2025-01-07 13:54:54,045 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:55:01,786 basehttp "POST /admin/aplicatie1/customuser/9/change/ HTTP/1.1" 302 0
INFO 2025-01-07 13:55:01,846 basehttp "GET /admin/aplicatie1/customuser/ HTTP/1.1" 200 21907
INFO 2025-01-07 13:55:01,913 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-01-07 13:55:08,238 views Utilizatorul viceroy s-a deconectat.
INFO 2025-01-07 13:55:08,252 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2025-01-07 13:55:08,299 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 13:55:19,953 views Autentificare reusita pentru utilizatorul grief.
INFO 2025-01-07 13:55:19,955 basehttp "POST /aplicatie1/user_login/ HTTP/1.1" 302 0
INFO 2025-01-07 13:55:20,004 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2429
INFO 2025-01-07 13:55:27,028 basehttp "GET /aplicatie1/lista_utilizatori/ HTTP/1.1" 200 1949
INFO 2025-01-07 13:55:31,089 views Utilizatorul grief s-a deconectat.
INFO 2025-01-07 13:55:31,104 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2025-01-07 13:55:31,157 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 13:55:38,217 views Autentificare reusita pentru utilizatorul viceroy.
INFO 2025-01-07 13:55:38,219 basehttp "POST /aplicatie1/user_login/ HTTP/1.1" 302 0
INFO 2025-01-07 13:55:38,270 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2657
INFO 2025-01-07 13:55:42,065 basehttp "GET /aplicatie1/lista_angajati/ HTTP/1.1" 200 2300
INFO 2025-01-07 13:55:43,473 basehttp "GET /aplicatie1/creare_angajati/ HTTP/1.1" 200 4660
INFO 2025-01-07 13:55:45,658 basehttp "GET /aplicatie1/profile/ HTTP/1.1" 200 2542
INFO 2025-01-07 13:55:46,636 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7954
INFO 2025-01-07 13:55:51,759 views Utilizatorul viceroy s-a deconectat.
INFO 2025-01-07 13:55:51,774 basehttp "GET /aplicatie1/user_logout/ HTTP/1.1" 302 0
INFO 2025-01-07 13:55:51,928 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 2059
INFO 2025-01-07 14:06:28,593 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 1942
INFO 2025-01-07 14:06:29,960 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7723
INFO 2025-01-07 14:06:40,528 basehttp "GET /aplicatie1/cos_virtual/ HTTP/1.1" 200 7684
INFO 2025-01-07 14:06:45,840 basehttp "GET /aplicatie1/user_login/ HTTP/1.1" 200 1942
